# Generated by Django 2.2.7 on 2019-11-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
    ]
