# Generated by Django 2.2.7 on 2019-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
