# Generated by Django 2.2.7 on 2019-12-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='ques',
        ),
    ]
