# Generated by Django 2.2.7 on 2019-12-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191206_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ques',
            new_name='name',
        ),
    ]
