# Generated by Django 2.2.7 on 2019-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('questions', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=100)),
            ],
        ),
    ]
