# Generated by Django 2.2.7 on 2019-12-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191206_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='name',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question',
        ),
    ]
