# Generated by Django 2.2.7 on 2020-01-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191206_1303'),
        ('core', '0007_profile_info'),
    ]

    operations = [
    ]
